# Generated by Django 5.1.2 on 2024-10-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.CharField(default='López Alcón', max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Tiempo completo'), ('part_time', 'Tiempo parcial'), ('contract', 'Contrato'), ('internship', 'Prácticas')], default='Tiempo Completo', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.CharField(default='Utrera', max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='posted_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='requirements',
            field=models.TextField(default='TBD'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='responsibilities',
            field=models.TextField(default='TBD'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(default='TBD'),
        ),
    ]
