# Generated by Django 5.1.2 on 2024-10-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_remove_aiquestion_candidate_jobapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
