# Generated by Django 5.1.2 on 2024-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_jobapplication_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_contact',
            field=models.CharField(choices=[('phone', 'Llamada telefónica'), ('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
