# Generated by Django 5.1.2 on 2025-02-06 10:34

import django.core.validators
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_candidate_created_at_candidate_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(max_length=255, upload_to=recruitment.models.Candidate.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), recruitment.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.CharField(default='Alpa Careers', max_length=100),
        ),
    ]
