# Generated by Django 5.1.2 on 2025-02-06 10:53

import django.core.validators
import recruitment.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_candidate_cv_alter_joboffer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(max_length=255, storage=storages.backends.s3.S3Storage(), upload_to=recruitment.models.Candidate.cv_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), recruitment.models.validate_file_size]),
        ),
    ]
